const bookMarkRoutes = require('express').Router();
const sequelize = require('../../db/db');
const Bookmark = require('../../models/Bookmark');
const {verifyLink} = require('../../helpers');



bookMarkRoutes.route('/')
    .get((req, res) =>{
      Bookmark.findAll()
        .then((data) => {
          res.status(200).json({
            data,
            status:'ok',
            message: 'all the bookmarks',
            errCode: null
          });
        })
        .catch((err) => {
          res.status(503).json({
            data:[],
            status: 'failed',
            message: 'service unavailable',
            errCode: 503
          })
        });
      })
    .post((req, res) => {
      // TODO data will come from user

      const name = req.body.name;
      const link = req.body.link;

      // server side validation for arguments

      if(name.length < 3 || name.length > 50) {
        return res.status(422).json({
          data: [],
          status: 'failed',
          message: 'invalid name sent, it should be 3-50 chars long',
          errCode: 422
        });
      }

      /**
       * check if the link received from user is a valid link or not
       */
      if(!verifyLink(link)){
        // similar to verifyLink(link) === false
        return res.status(422).json({
          data: [],
          status: 'failed',
          message: 'invalid link sent',
          errCode: 422
        });
      }

      const newBookmark = Bookmark.build({
        name,
        link,
        // time will always generated by the server
        created_at: new Date().toDateString() 
      }); 

      Bookmark.sync({force: false})
      .then(() => {
        newBookmark.save()
        .then((data) => {
          // data saved successfully, send response to user
          res.status(200).json({
            data,
            status: 'ok',
            message: 'saved bookmark',
            errCode: null
          });
          //console.log(data);
        })
        .catch((err) => {
          console.log(err); 
          
          if(err.original.code === 'ER_DUP_ENTRY'){
            return res.status(409).json({
              data: [],
              status: 'failed',
              message: 'duplicate data',
              errCode: 409
            });
          }
         return res.status(503).json({
            data: [],
            status: 'failed',
            messsage: 'service unavailable',
            errCode: 503
          });
          
        });
      })
      .catch(err => console.log(err));
    });


bookMarkRoutes.route('/:id')
  .get((req, res) => {
    const id = parseInt(req.params.id);
    if(isNaN(id)) {
      return res.status(422).json({
        data: [],
        status: 'failed',
        messsage: 'invalid id sent',
        errCode: 422
      });
    }
    Bookmark.findAll({
      where: {
        id: id
      }
    })
    .then((data) => {
      //console.log('data = ',data);
      if(data.length < 1){
        return res.status(404).json({
          data: [],
          status:'failed',
          message: 'data not found',
          errCode: 404
        });
      }
      return res.status(200).json({
        data,
        status:'ok',
        message:'found data',
        errCode: 200
      });
    })
    .catch((err) => {
      console.log(err);
      return res.status(503).json({
        data: [],
        status: 'failed',
        message: 'service unavailable',
        errCode: 503
      });
    })
  })
  .delete((req, res) => {
    let _id = parseInt(req.params.id);

    if(isNaN(_id)){
      return res.status(422).json({
        data: [],
        status: 'failed',
        message: 'invalid id',
        errCode: 422
      });
    }

    Bookmark.destroy({
      where: {
        id: _id
      }
    })
    .then((data) => {
      return res.status(200).json({
        data: [], 
        status: 'ok',
        message: 'deleted successfully',
        errCode: null
      });
    })
    .catch((err) => {
      return res.status(503).json({
        data: [],
        status: 'failed',
        message: 'service unavailable',
        errCode: 503
      });
    });
  })
  .patch((req, res) => {
    console.log(req.body);
    console.log(req.params);
  
    const id   = parseInt(req.params.id);
    const name = req.body.name;
    const link = req.body.link;
    if(!name && !link ){
      return res.status(422).json({
        data: [],
        status: 'failed',
        message: 'missing parameter',
        errCode: 422
      });
    }
    const updateList = {};

    if(isNaN(id)){
      return res.status(422).json({
        data: [],
        status: 'failed',
        message: 'invalid id',
        errCode: 422
      });
    }

    if(name){
      updateList.name = name;
    }

    if (link) {
      updateList.link = link;
    }

    Bookmark.update(
      updateList,
      {
      where: {
        id: id
      }
    })
    .then((data) => {
      return res.status(200).json({
        data,
        status: 'ok',
        message: 'update message',
        errCode: 200
      });
    })
    .catch((err) => {
      console.error('**Error => ', err);

      if(err.original.code === 'ER_DUP_ENTRY'){
        return res.status(409).json({
          data: [],
          status: 'failed',
          message: 'duplicate data',
          errCode: 409
        });
      }
      return res.status(503).json({
        data: [],
        status: 'failed',
        message: 'service unavailable',
        errCode: 503
      });
    });
  });


module.exports = bookMarkRoutes;